/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreateSmsProvider: typeof import('./src/components/SmSys/Sections/ManageSmsProviders/CreateSmsProvider.vue')['default']
    Loading: typeof import('./src/components/App/Loading.vue')['default']
    ManageSmsProviders: typeof import('./src/components/SmSys/Sections/ManageSmsProviders/ManageSmsProviders.vue')['default']
    Modal: typeof import('./src/components/App/Modal.vue')['default']
    NoOrganizationAlert: typeof import('./src/components/App/NoOrganizationAlert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./src/components/App/Sidebar/SidebarItem.vue')['default']
    TheSidebar: typeof import('./src/components/App/Sidebar/TheSidebar.vue')['default']
  }
}
